### PR TITLE
allow yaml files of same name in different dirs or file extensions

### PR DESCRIPTION
**Pull request by jumanjiman**
allow yaml files of same name in different dirs or file extensions

* Remove assumption that thing.yaml and thing.yml don't both exist.

* Allow same file name in multiple paths, such as
  - hieradata/idunno/thing.yaml
  - hieradata/common/thing.yaml

New unit tests:

    RSpecPuppetUtils::HieraData::YamlValidator
      #load_data
        with valid yaml
          should load yaml data from files with same name but different dir
          should load yaml data from files with same name but different ext

To accomplish this, we store the subpath (as opposed to just the base name)
in yaml validator data and adjust existing unit tests for the subpath.

The payoff is that we can now validate _all_ files that may
exist in somebody's hieradata yaml tree.

### CODE REVIEW

**Comment by jumanjiman** [comment]
@TomPoulton bump?

**Comment by TomPoulton** [comment]
Hi @jumanjiman, we're having some issues with the WiFi at work, if it doesn't get fixed today I'll try and find some time tonight to test and merge

**Comment by jumanjiman** [comment]
thanks @TomPoulton ! this will be a big help for us.

**Comment by TomPoulton** [comment]
Merged and published. Thanks for this, I remember writing the initial version thinking "I'll come back to this later"!

**Comment by jumanjiman** [comment]
woot!

**Pull request merged**
